smtp.auth.user=sergii.puzyrov@gmail.com
smtp.auth.password=<secret>
smtp.subject=Welcome e-mail
smtp.from=SVPuzyrov
smtp.recipients=pp002831@gmail.com,goldbyts@gmail.com
smtp.content.html.template.name=campaignmonitor